---
- apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0C49F3730359A14518585931BC711F9BA15703C6

- name: MongoDB ROLE | Adding mongodb sources.list deb url
  lineinfile: dest=/etc/apt/sources.list line="deb http://repo.mongodb.org/apt/debian {{ ansible_distribution_release }}/mongodb-org/3.4 main"
  when: ansible_distribution == "Debian"

- name: MongoDB ROLE | Adding mongodb sources.list deb url
  lineinfile: dest=/etc/apt/sources.list line="deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/3.4 multiverse"
  when: ansible_distribution == "Ubuntu"

- name: MongoDB ROLE | Updating apt cache
  apt:
    update_cache: yes

- name: MongoDB ROLE | Install MongoDB
  apt: name={{ item }} force=yes
  with_items:
   - mongodb-org

- name: MongoDB ROLE | Ensure mongod is restarted
  action: service name=mongod state=restarted
