---
- apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0C49F3730359A14518585931BC711F9BA15703C6

- name: MongoDB ROLE | Adding mongodb sources.list deb url
  lineinfile: dest=/etc/apt/sources.list line="deb http://repo.mongodb.org/apt/debian {{ ansible_distribution_release }}/mongodb-org/3.4 main"
  when: ansible_distribution == "Debian"

- name: MongoDB ROLE | Adding mongodb sources.list deb url
  lineinfile: dest=/etc/apt/sources.list line="deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/3.4 multiverse"
  when: ansible_distribution == "Ubuntu"

- name: MongoDB ROLE | Updating apt cache
  apt:
    update_cache: yes

- name: MongoDB ROLE | Install MongoDB
  apt: name={{ item }} force=yes install_recommends=yes
  with_items:
   - mongodb-org
   - python-pip

- name: Install pymongo
  pip: name=pymongo

- template:
    src: ../templates/etc/mongod.conf.default.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: 0644
  become: true


- name: MongoDB ROLE | Ensure mongodb is restarted
  action: service name=mongod state=restarted

- mongodb_user:
    database: "{{ default_mongodb_admin_db }}"
    name: "{{ default_mongodb_root_login }}"
    password: "{{ default_mongodb_root_password }}"
    roles: root
    state: present

- mongodb_user:
    database: "{{ default_mongodb_admin_db }}"
    name: "{{ default_mongodb_user_login }}"
    password: "{{ default_mongodb_user_password }}"
    roles: clusterAdmin,readAnyDatabase
    state: present

- template:
    src: ../templates/etc/mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: 0644
  become: true

- template:
    src: ../templates/etc/init.d/disable-transparent-hugepages.j2
    dest: /etc/init.d/disable-transparent-hugepages
    owner: root
    group: root
    mode: 0755
  become: true

- name: Enable tph disabling service
  shell: update-rc.d disable-transparent-hugepages defaults

- name: MongoDB ROLE | Ensure tph is restarted
  action: service name=disable-transparent-hugepages state=restarted

- name: MongoDB ROLE | Enable mongod autostart
  systemd:
    name: mongod
    state: started
    enabled: true
  when: ansible_distribution == "Ubuntu"

- name: MongoDB ROLE | Ensure mongod is restarted
  action: service name=mongod state=restarted