---
- apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0C49F3730359A14518585931BC711F9BA15703C6

- name: MongoDB ROLE | Adding mongodb sources.list deb url
  lineinfile: dest=/etc/apt/sources.list line="deb http://repo.mongodb.org/apt/debian {{ debian_codename }}/mongodb-org/3.4 main"

- name: MongoDB ROLE | Updating apt cache
  apt:
    update_cache: yes

- name: MongoDB ROLE | Install MongoDB
  apt: name={{ item }} force=yes
  with_items:
   - mongodb-org

- name: MongoDB ROLE | Ensure mongod is restarted
  action: service name=mongod state=restarted
